import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/shared/header";
import { Footer } from "@/components/shared/footer";
import HeroSection from "@/components/shared/hero-section";

const nunito = Nunito({
  subsets: ['latin-ext'],
  variable: '--font-nunito',
  weight: ['400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: "TESGART",
  description: "Generated by create next app", //needable to ceo to read the page 
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="tr">
      <body className={nunito.className}> 
        <main className='pt-32 min-h-screen'>{/*min height 100vh*/}
          <Header />
         {children}
          <Footer />
          </main> 
      </body>
    </html>
  );
}
